### ISSUE TITLE
Access Denied error

### ISSUE THREAD

**Issue by Jarsky** [DIGITALCRIMINALS/OnlyFans#850]
Using: Docker on Linux (20.10.17)
This just started yesterday:

```
Skipping virtualenv creation, as specified in config file.
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<JobManager.worker() running at /usr/local/lib/python3.10/site-packages/ultima_scraper_api/managers/job_manager/job_manager.py:48> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-27' coro=<JobManager.worker() running at /usr/local/lib/python3.10/site-packages/ultima_scraper_api/managers/job_manager/job_manager.py:48> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-52' coro=<JobManager.worker() running at /usr/local/lib/python3.10/site-packages/ultima_scraper_api/managers/job_manager/job_manager.py:48> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-77' coro=<JobManager.worker() running at /usr/local/lib/python3.10/site-packages/ultima_scraper_api/managers/job_manager/job_manager.py:48> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-102' coro=<JobManager.worker() running at /usr/local/lib/python3.10/site-packages/ultima_scraper_api/managers/job_manager/job_manager.py:48> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-127' coro=<JobManager.worker() running at /usr/local/lib/python3.10/site-packages/ultima_scraper_api/managers/job_manager/job_manager.py:48> wait_for=<Future pending cb=[Task.task_wakeup()]>>

Access denied.
Archive Completed in 0.15 Minutes
Error: {'code': 0, 'message': 'Access denied.'}
```

It was working fine then started not to work. I thought it was an expired session so logged off and logged back on to OF and got the new cookie session info. Stopped the container, updated the auth.json and restarted the container but same error. 

I've tried removing the Docker container/image completely Recloned the repo, rebuilt the docker container/image. 
Updated the auth.json and it still gives the access denied error. 

This is how I upgrade it:

**digitalcriminals.sh**
```
#!/bin/bash
cd /opt/onlyfans
rm -rf OnlyFans
git clone https://github.com/DIGITALCRIMINALS/OnlyFans.git
docker container stop onlyfans && docker rmi onlyfans
docker-compose up -d --build

```

**docker-compose.yml**
```
version: "3.2"
services:
  onlyfans:
    image: onlyfans:latest
    container_name: onlyfans
    hostname: onlyfans
    build:
      context: './OnlyFans/'
    volumes:
      - ./config/__settings__:/usr/src/app/__settings__
      - ./config/__user_data__:/usr/src/app/__user_data__
      - /mnt/share/DMP/sites:/usr/src/app/__user_data__/sites
    restart: always
networks:
 default:
   external:
      name: myNetwork
```

auth.json example
```
{
  "auth": {
    "username": "default",
    "cookie": "auth_id=1234567890; sess=my_session_id_from_cookie; auth_hash=; auth_uniq_1234567890=; auth_uid_1234567890=; aws-waf-token=;",
    "x_bc": "my_xbc_string_from_the_header",
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36",
    "email": "myemail@address.com",
    "password": "mypasswordhere",
    "hashed": false,
    "support_2fa": true,
    "active": true
  }
}
```
